# Basic site setup
title: Welcome to my blog
description: Welcome to the world of DevOps, scripting, and much more for HPE products and solutions! 
  This blog is your one-stop destination for insightful articles, tutorials,
  and best practices on all things related to DevOps, scripting, and how it 
  connects with HPE products and solutions.
accent_colour: "#acacac"
theme_version: 1.0.15
url: https://jullienl.github.io

# Optional native feature customisation (delete to turn off)
table_of_contents_header: "Jump to:"
table_of_contents_collapsible: true
post_end_promo: <i><b>Enjoyed this article? Discover more on the <a href="https://developer.hpe.com/">HPE Developer Community</a> site,<br> your hub for all HPE software-related content!</b></i>
google_analytics: G-TKGDJPHXCL
replace_read_time_with_word_count: false
show_excerpts_html: true
open_external_links_in_new_tab: true

# Third party feature customisation (delete to turn off)
giscus_repo: jullienl/jullienl.github.io
giscus_repo_id: R_kgDOKG9STg
giscus_category: Comments
giscus_category_id: DIC_kwDOKG9STs4CfLVZ
# kofi_id: internethistory
# kofi_button_text: Tip on Ko-fi
# kofi_floating_text: Tip / Suggest

# Network site picker
network:
  # - { name: Programming, url: "https://blog.jakelee.co.uk", colour: "#2a7ae2" }
  # - {
  #     name: Internet History,
  #     url: "https://history.jakelee.co.uk",
  #     colour: "#075e78",
  #   }
  # - { name: Theme, url: "https://minima.jakelee.co.uk", colour: "#951A00" }
  # - { name: Cat Charity, url: "https://news.codecured.org", colour: "#111b6d" }
  # - {
  #     name: Fragments,
  #     url: "https://fragments.jakelee.co.uk",
  #     colour: "#ad33a9",
  #   }
  # - { name: Everything Else, url: "https://jakelee.co.uk", colour: "#acacac" }

# Social / dark mode settings
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/jullienl" }
    - { platform: youtube, user_url: "https://youtube.com/@LionelJullien" }  
    - {
        platform: postman,
        user_url: "https://www.postman.com/jullienl/workspace/lionel-jullien-s-public-workspace/overview",
      }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/lionel-jullien-793b56" }
    - {
        platform: email,
        user_url: "mailto:lio@hpe.com",
        user_title: "lio@hpe.com",
      }
    - { platform: rss, user_url: "/feed.xml", user_title: "RSS Feed" }
 
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

###
# Below here probably doesn't need changing #
###

# Site settings
permalink: /:title/
timezone: Europe/Paris
title-logo: #/assets/images/favicon/favicon-32x32.png


# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination settings
paginate: 5
paginate_path: page/:num/

# Syntax highlighter settings
kramdown:
  syntax_highlighter_opts:
    default_lang: kotlin
    guess_lang: true

# New fields not defaulted by jekyll-new with the minima theme
# Add a copyright. A copyright symbol and year will be added automatically
# copyright: Company name, Inc.
copyright: "Hewlett Packard Enterprise"